### ISSUE TITLE
ready for review

### ISSUE THREAD

**Issue by b00y0h** [b00y0h/codepath_week2_assignment_carousel#1]
@adeysalyards

**Comment by adeysalyards** [comment]
Looks good! Have you considered adding this cool intro? https://vimeo.com/103390379

Were there any issues with the guides for this assignment?

**Comment by b00y0h** [comment]
@adeysalyards yeah, saw that option but didn't have time to implement. never saw that video though. I'll see if I can implement that on my flight to NY today.

I don't think the code for the keyboard show/hide is correct. When you go from one input field to the next, it transitions again. Pushing things up further.

**Comment by adeysalyards** [comment]
Hm. Let's review on Wednesday.
